types:
  supported:
    - ".mp4"
    - ".mpg"
    - ".mov"
    - ".avi"
    - ".wmv"
    - ".mkv"
  unsupported:

# watch out - syntax is slightly different than above
shortcuts:
  clip: # file level navigaton
    next: "." # can also include joystick or osc fields
    previous: ","
    random: "/"
    super_random: "`" # random from the whole library
    rate_double: "="
    rate_half: "-"
    rate_1.5: "+"
    rate_0.75: "_"
    rate_default: "0"
    dir_flip: "o" # swap the direction
    palindrome: "p"
    jump_random: "j" # jump to random position
    hard_sync: "H"
    resync: "r"
    zero: "z" # jump to zero
  kit:
    next: "]" # can also include joystick or osc fields
    previous: "["
    random: "ยง"

display:
  size:
    width: 800
    height: 600
